name: generate pacman game

on:
  schedule: # run automatically every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch: # allows to manually run the job at any time
  push: # run on every push on the main branch
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./src/core

      - name: Generate pacman-contribution-graph.svg
        run: |
          mkdir -p dist
          # light mode
          node ./cli/index.js \
            --platform github \
            --username "${{ github.repository_owner }}" \
            --gameTheme github \
            --output dist/pacman-contribution-graph.svg
          # dark mode
          node ./cli/index.js \
            --platform github \
            --username "${{ github.repository_owner }}" \
            --gameTheme github-dark \
            --output dist/pacman-contribution-graph-dark.svg
        working-directory: ./src/core

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: src/core/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
