name: generate pacman game

on:
  schedule:
    - cron: "0 */24 * * *"  # Run daily
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./src/core

      - name: Generate Pac-Man Contribution SVGs
        run: |
          mkdir -p dist
          # Light theme
          node ./cli/index.js \
            --platform github \
            --username "${{ github.repository_owner }}" \
            --gameTheme github \
            --output dist/pacman-contribution-graph.svg
          # Dark theme
          node ./cli/index.js \
            --platform github \
            --username "${{ github.repository_owner }}" \
            --gameTheme github-dark \
            --output dist/pacman-contribution-graph-dark.svg
        working-directory: ./src/core

      - name: List generated files
        run: ls -R src/core/dist

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: src/core/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
